
services:

  #servicio-eureka-server-node:
   # image: eureka
   # container_name: servicio-eureka-server-node
   # ports:
   #   - 8761:8761
  todo-team-resource:
    build: ./resource
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
  todo-team-security:
    build: ./security
    restart: unless-stopped
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
  todoteam-node:
    image: todoteam
    container_name: todoteam-node
    ports:
      - 4200:4200
    restart: on-failure:10
    
    
    

